export enum SocketEvent {
  banUser = "banuser",
  chatMessage = "chatmessage",
  cheer = "cheer",
  close = "close",
  deleteChatMessage = "deletechatmessage",
  error = "error",
  follow = "follow",
  open = "open",
  raid = "raid",
  raw = "raw",
  shoutOut = "shoutout",
  sub = "sub",
  timeoutUser = "timoutuser",
  timer = "timer",
}
