export enum SocketEvent {
  announceGiveaway = "announcegiveaway",
  banUser = "banuser",
  chatMessage = "chatmessage",
  cheer = "cheer",
  close = "close",
  deleteChatMessage = "deletechatmessage",
  drawGiveaway = "drawgiveaway",
  endGiveaway = "endgiveaway",
  enterGiveaway = "entergiveaway",
  error = "error",
  follow = "follow",
  open = "open",
  raid = "raid",
  raw = "raw",
  shoutOut = "shoutout",
  startGiveaway = "startgiveaway",
  sub = "sub",
  timeoutUser = "timoutuser",
  timer = "timer",
}
